### ISSUE TITLE
Als Admin "aktualisiert" die Seite zu oft

### ISSUE THREAD

**Issue by thewavelength** [Skill3t/Tele-Schocken#11]
Bei der Eingabe der Punkte/Chips, die einem Spieler zugewiesen werden sollen, kann es passieren, dass die Seite aktualisiert und die Eingabe somit verloren ist. Kann nervig sein auf Dauer.

**Comment by Skill3t** [comment]
Kannst du hier noch mal genauer beschreiben wann das passiert? Sobald der Admin die Chips verteilt sollte das Ergebniss bei allen Spielern angezeigt werden.

**Comment by thewavelength** [comment]
Ich selber war noch kein Admin, jedoch wurde mir berichtet, dass wenn eine Eingabe im Inputfeld getätigt wird, dass es häufiger passiert sei, dass sich die Seite aktualisiert hat und die Eingabe dann natürlich verschwunden war, weil die Chips noch nicht zugewiesen wurden.

Leider kann ich Dir keine bessere Beschreibung liefern. Falls es mir mal passiert, beobachte ich das Mal.

**Comment by Skill3t** [comment]
Das sollte nur passieren wenn man die Seite neu läd. Ja berichte gerne mal.
