### ISSUE TITLE
Reihenfolge der Würfe sichtbar machen

### ISSUE THREAD

**Issue by thewavelength** [Skill3t/Tele-Schocken#12]
Idee: Reihenfolge der Würfe sichtbar machen, sodass immer klar ist, wer wann dran war, um in Pattsituationen besser entscheiden zu können.

**Comment by Skill3t** [comment]
Das ist meiner Meinung nach heute schon gegeben. Der Spieler der die Runde begonnen hat ist blau hinterlegt und die Reigenfolge geht von dort nach unten. Am Ende der Liste fängt es oben wieder an. Oder hast du eine bessere Idee?

**Comment by thewavelength** [comment]
Okay. Das ist uns gar nicht aufgefallen. Dann nichts für ungut!
