### ISSUE TITLE
Einführung eines Finales

### ISSUE THREAD

**Issue by christianlohr9** [Skill3t/Tele-Schocken#13]
Hey Leute,
ihr schreibt zwar schon, dass es für die Leute zu langweilig ist den anderen im Finale zuzusehen, aber genau diese Funktion bräuchte ich für ein phänomenales Event ;)

Ist es möglich ein FInale und den Reset der Hälften zu etablieren?

Gruß
Christian

**Comment by Skill3t** [comment]
Der Aufwand ist nicht ganz unerheblich. Ich schau mal wann ich das hin bekomme. Würde dann als option sein die man im Warteraum einstellen kann.

**Comment by christianlohr9** [comment]
Uns fällt gerade auf, dass für diesen Fall im Prinzip schon mein Vorschlag in Issue #14 greifen würde, in dem ich auf den Button aus #4 verweise. 
Jetzt wirds wild hier ;)

Wenn jeder Spieler jederzeit Ende überspringen kann, dann kann auch ohne eine eigene Programmierung ein Finale gespielt werden 👍🏽

**Comment by Skill3t** [comment]
Finale ist jetzt richtig eingebaut!
