### ISSUE TITLE
Runde aussetzen als Spieler

### ISSUE THREAD

**Issue by christianlohr9** [Skill3t/Tele-Schocken#15]
Ich vermute das coding sollte ähnlich dem des Issues #14 sein.

Wenn ein Spieler gerade auf Toilette geht oder Anschiss von der Frau kriegt, warum er sich wieder mal die Rinne bis zum Anschlag verzinkt, dann wäre es hilfreich als Admin den Spieler sozusagen "inactive" setzen zu können.

**Comment by Skill3t** [comment]
Hey es gibt ja die Möglichkeit einen Spieler aus dem Spiel zu entfernen. So kannst du den Kumpel entfernen und später wieder hinzufügen.
