### ISSUE TITLE
Würfelgeräusche entfernen

### ISSUE THREAD

**Issue by christianlohr9** [Skill3t/Tele-Schocken#17]
Ist es möglich den Ton auszuschalten?

**Comment by Skill3t** [comment]
Kannst du ja einfach im Broswer austellen. Hier zum Beispiel beim Firefox. 
<img width="480" alt="Bildschirmfoto 2020-12-29 um 21 19 55" src="https://user-images.githubusercontent.com/6004614/103311873-c4b99080-4a1b-11eb-8258-00edb48a7b50.png">

**Comment by christianlohr9** [comment]
Ohje, das war einfach. Danke!!!

**Comment by Skill3t** [comment]
Freut mich das ich helfen konnte.
