### ISSUE TITLE
Zusammengewürfelte Straße

### ISSUE THREAD

**Issue by christianlohr9** [Skill3t/Tele-Schocken#18]
Am Ende ist nicht mehr ersichtlich, ob eine Straße zusammengewürfelt ist oder nicht.
Ich weiß, dass es in manchen (wirklich weltfremden) Gegenden zusammengewürfelte Straßen gibt.

Aber ist es möglich rausgelegte Würfel bspw. farblich kenntlich zu machen?
Dann hätte die rausgelegte 1 bspw. eine Farbe und die anderen beiden nicht.

**Comment by Skill3t** [comment]
Also wenn man in der Kneipe spielt wird das ja auch nicht angezeigt. Wenn man aufpasst sieht man ja wenn ein Würfel vorher raus gestellt wurde. Hier spalten sich halt die Geister. Die eine Hälfte der Spieler will mehr Komfort die andere so weit wie möglich am Kneipenspiel. 

P.S. Wir sind auch Team Straße zusammen würfeln geht gar nicht. 😅

**Comment by christianlohr9** [comment]
Ok, fair!

Fürs PS ein Bier an den Enwickler :D

**Comment by Skill3t** [comment]
😅 Vielen Vielen Dank! 🍻
