### ISSUE TITLE
Spieler mit Schock-Out behält Chips und gewinnt

### ISSUE THREAD

**Issue by flok89** [Skill3t/Tele-Schocken#19]
Hallo,

erstmal vielen Dank für das Entwickeln des Spiels. Tele-Schocken hat uns schon einige Abende während Corona gerettet. Super Job. 👍 

Nun zu meinem Feature Request. Bei uns (in Nord-Württemberg) gibt es die Regel, dass derjenige, der einen Schock-Out würfelt, sofort das Spiel gewinnt, in der nächsten Runde übersprungen wird, aber dabei alle seine Chips behält. 

Ich weiß, dass es viele regional unterschiedliche Regeln gibt, aber ggf. kannst du die Einstellung irgendwo optional hinterlegen.

**Comment by Skill3t** [comment]
Vielen Dank für dein super feedback. 
Da diese Regel recht exotisch ist, plane ich leider nicht diese umzusetzen. Wenn aber einer von eurer Runde Python programmieren kann, kann er oder sie gerne einen pull request machen dann nehme ich das mit ins Spiel auf. Am besten als Option die man in dem Warteraum setzen kann.
