### ISSUE TITLE
"Ende drücken" überspringen

### ISSUE THREAD

**Issue by thewavelength** [Skill3t/Tele-Schocken#4]
Idee: eine Option zum automatischen Auslassen von Spielern, die 0 Chips haben, wenn alle Chips verteilt wurden.

Aktuell: jeder Spieler muss jede Runde auf Ende drücken, wenn er nicht mitspielt.

**Comment by Skill3t** [comment]
Ja das ist beabsichtigt. So wird ein Einwerfen ermöglich. Ich überlege mal eine Option einzubauen.

**Comment by Skill3t** [comment]
Was hälst du davon das unter ende eine checkbox erscheint wenn man selber nicht mehr in der Runde ist (keine Chips auf dem stapel und man selber hat auch keine Chips). Die kann man dann anklicken und man wird übersprungen bis die Runde zu ende ist. Finde das ist ein guter Kompromiss.

**Comment by thewavelength** [comment]
Klingt gut!

**Comment by Skill3t** [comment]
So ist nun umgesetzt. Aktuell noch als beta. Darf gerne getestet werden. 

<img width="642" alt="Bildschirmfoto 2021-01-03 um 21 16 10" src="https://user-images.githubusercontent.com/6004614/103488516-74707300-4e0d-11eb-8a29-2c33dcc66f23.png">

**Comment by christianlohr9** [comment]
Nicht, dass es wichtig wäre 😆 
Mehr so der Alman-Hinweis: Im Push-Up steht "suscess".

**Comment by Skill3t** [comment]
Danke ist angepasst!
