### ISSUE TITLE
Aufzudeckende Würfel auswählbar machen

### ISSUE THREAD

**Issue by thewavelength** [Skill3t/Tele-Schocken#6]
Idee: aufzudeckende Würfel auswählbar machen.

Aktuell: alle Würfel werden aufgedeckt.

**Comment by Skill3t** [comment]
Rausgestellt Würfel werden automatisch aufgedeckt. Und am ende der Runde müssen alle würfel aufgedeckt werden.

**Comment by thewavelength** [comment]
Sorry, hier nochmal die genauere Beschreibung:

> Ich hatte das Problem, dass ich einen Würfel draußen gelassen habe und nach dem zweiten Wurf wieder rein gelegt habe. Dieser wurde dann weiterhin als aufgedeckt angezeigt, was nicht sein sollte.

**Comment by Skill3t** [comment]
Hab es noch mal versucht nachzuvollziehen. Das ding ist wir Spielen immer was draußen ist bleibt draußen. Hab den Fehler aber gefunden und gefixt. [Fix](https://github.com/Skill3t/Tele-Schocken/commit/9796b811a5abac5280fe874ddca8b0da26cd1c9e)
