### ISSUE TITLE
Aktualisierung des Spielstates

### ISSUE THREAD

**Issue by thewavelength** [Skill3t/Tele-Schocken#7]
Idee: komplette Live-Aktualisierung des Spielstates.

Aktuell: manchmal (?) muss F5 gedrückt werden.

**Comment by Skill3t** [comment]
Akutell sollte das nur vorkommen wenn man den Admin wechselt oder Spieler aus dem Spiel wirft. Ist denke ich vertretbar. Kannst aber gerne ein pull request schreiben ;-)
