### ISSUE TITLE
Bei Rundenstart alle Würfel zum würfeln automatisch auswählen

### ISSUE THREAD

**Issue by thewavelength** [Skill3t/Tele-Schocken#8]
Idee: bei Rundenstart alle Würfel zum würfeln automatisch auswählen.

Aktuell: die zuletzt markierten Würfel bleiben bestehen.

**Comment by Skill3t** [comment]
Gute Idee ich schau mal das ich das zwischen den Tagen umgetzte bekomme bin die nächste zwei Wochen leider stark eingebunden.

**Comment by Chris-197** [comment]
Hi Skill3t! Wir haben dein Online-Meiern heute entdeckt und feiern das richtig!!! Danke dafür! 👍 
Wir hatten die Idee, dass dir dann auch "ein Würfel runtergefallen ist" und eine entsprechende Meldung angezeigt wird und dann ne Schnapsrunde fällig wird, wenn du vergisst die Würfel zur neuen Runde wieder in den Becher zu packen.

**Comment by Skill3t** [comment]
Interessante Idee aber was haltet ihr von der Variante die @thewavelength vorgeschlagen hat? In der Kneipe vergisst man ja auch nicht einen Würfel in den Becher zu packen 😅

**Comment by Chris-197** [comment]
Ja haste recht. Wenn der Würfel runterfällt dann beim reinpacken in den Becher bei fortgeschrittener Stunde 😊

**Comment by Skill3t** [comment]
[https://github.com/Skill3t/Tele-Schocken/commit/ac75627972d484e2bb4f87500bea1416af86772e](ist verbessert)
