### ISSUE TITLE
Automatisierungs-/Regel-API

### ISSUE THREAD

**Issue by thewavelength** [Skill3t/Tele-Schocken#9]
Ich finde es super, dass Tele-Schocken super flexibel ist, sodass der Administrator alles manuell machen kann. So können fast alle Spielvarianten abgebildet werden.

Super wäre, wenn Regeln hinterlegt werden können, die der Admin auswählen kann. Falls man eine Variante spielen möchte, die bereits hinterlegt sind, können einige Dinge automatisiert werden.

Beispielsweise:

- Automatische Punkteverteilung
- Automatisches Aufdecken der Würfel aller Spieler

**Comment by Skill3t** [comment]
Da es sehr viele unterschiedliche Spielprinzipien gibt, ist das sehr aufwendig das in feste Regeln zu gießen. Kannst hierzu gerne einen pull request schreiben aber das denke ich werde ich nicht umsetzen. Sorry
